<p>
You are now signed in as a user.
</p>

<p>
Go to <%= link_to "simulate_devise_timeout", "/simulate_devise_timeout" %> and
you will be timed out by devise (user timeout set to 1 second). Look at the logs
generated by lograge. Status code is 0.
</p>

<p>
Go to <%= link_to "simulate_regular_401", "/simulate_regular_401" %> you will
not be timedout (we tell devise to skip the timeout). Instead, we render nothing
with a status of 401. Looks at the logs, it shows status of 401.
</p>

<p>
<strong>
  So the question is, why doesn't the 401 Unauthorized response generated by
  devise get logged as status=401?
</strong>
</p>
